# Generated by Django 4.2.4 on 2023-09-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemonapp', '0003_menu_rename_guest_count_booking_guest_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_item_description',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
