# Generated by Django 4.2.4 on 2023-09-25 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lemonapp', '0004_menu_menu_item_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='menu_item_description',
            new_name='description',
        ),
    ]
