# Generated by Django 4.2.4 on 2023-09-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemonapp', '0005_rename_menu_item_description_menu_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='guest_number',
            new_name='guest_count',
        ),
        migrations.AddField(
            model_name='booking',
            name='reservation_time',
            field=models.DateField(auto_now=True),
        ),
    ]
